<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://www.nitobi.com" prefix="ntb" %>
<html>
<head>
<link type="text/css" rel="stylesheet" href="../../../common/style/samples.css"></link>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Classic</title>
</head>
<body>
<p class="intro">This sample illustrates the use of Paging and Classic Search Mode. 
You can expand the page size by pressing the page button or using PageDn on your keyboard. 
All aspects of ComboBox operation are keyboard accessible.
In classic search mode we have access to traditional combobox paging capabilities. A paging 
button appears that can be used to expand the local list based on the current search string. 
You can also page using the PageDn key or by keying down the list to the bottom.</p>
<ul class="instructions">
	<li>Put your cursor in the text box and start typing. </li>
	<li>The listbox will contain selections from the database based on your search string.</li>
</ul>
<p class="notes">In this demo, we can submit the form containing the combobox. You will see the form values generated by the combobox appear at the bottom of the page. </p>

<form method=get>
	<!-- A list which allows paging and search. The datasource is a separate asp file. -->
	<ntb:combo id="myCombo"
			mode="classic" 
			toolkitjsurl="../../../common/script/nitobi.toolkit.js"
			componentcssurl="../../../common/style/nitobi.combo.css"
			componentjsurl="../../../common/script/nitobi.combo.js">
			<ntb:combotextbox
			   width="200px"
			   datafieldindex="0">
		</ntb:combotextbox>
		<!-- A list which allows paging and search. The datasource is a separate asp file. -->
		<ntb:combolist
			width="370px"
			height="205px"
			datasourceurl="get"
			pagesize="11">
            <ntb:combocolumndefinition columntype="IMAGE" width="16px" datafieldindex="4" headerlabel="<img src=scustomerimage.gif>"></ntb:combocolumndefinition>
			<ntb:combocolumndefinition width="130px" headerlabel="Customer List" datafieldindex="0" ></ntb:combocolumndefinition>
			<ntb:combocolumndefinition width="200px" datafieldindex="1"></ntb:combocolumndefinition>
		</ntb:combolist>
	</ntb:combo>
  <input type=submit value="Submit this form" style="margin-left:10px;">
</form>
<script language="javascript">

if (window.location.search.length > 0)
{
	document.write("<p>Form post fields for myCombo:</p><div style='background-color: #f0f0f0; padding:10px; padding-left: 20px;'><p>");
	document.write(window.location.search.replace(/\&/g, "<br>").replace("?", "").replace(/=/g, " = ").replace("%40", "@"));
	document.write("</p></div>");
}

</script>
</body>
</html>